### ISSUE TITLE
canton_design_system repo is not available

### ISSUE THREAD

**Issue by rimmer** [31Carlton7/flutter_news_app#1]
[canton_design_system repo](https://github.com/31Carlton7/canton_design_system) is not available anymore. When navigating to it, just gives 404.

**Comment by 31Carlton7** [comment]
Recently I just changed the visibility of the repository to private. I don't believe it's in a stage where it can or should be public as of now, but in the far or near future I may consider making it public again.

**Comment by rimmer** [comment]
Thanks @31Carlton7, this is absolutely up to you do decide what to do with your repos.
However, it makes this repo's usage limited to "snippets", one cannot build and feel the app anymore. 

We are having a hackathon right now I was looking for a sample app that we can demo our idea on and I was quite upset of the fact I cannot build the app anymore :) No worries, just sharing my experience :)

Perhaps would like to reflect the situation in README. 
UPD: I see you have already updated README, thank you

**Comment by 31Carlton7** [comment]
Don't worry, I will be putting back up later today after I took some time to reflect on the decision however, it remain unavailable on pub.dev
